database:
    driver: 'pdo_mysql'
    host: 'localhost'
    dbname: 'eccube3'
    port: '3306'
    user: 'root'
    password : 'root'
    charset: utf8
    defaultTableOptions: { collate: utf8_general_ci }
