- id: product
  name: Product Management
  has_child: true
  icon: cb-tag
  child:
      - id: product_master
        name: Product Master
        url: admin_product
      - id: product_edit
        name: Product Register
        url: admin_product_product_new
      - id: class_name
        name: Product Class Register
        url: admin_product_class_name
      - id: class_category
        name: Category Register
        url: admin_product_category
      - id: product_csv_import
        name: Product CSV Registration
        url: admin_product_csv_import
      - id: category_csv_import
        name: Category CSV Registration
        url: admin_product_category_csv_import
- id: order
  name: Order Management
  has_child: true
  icon: cb-shopping-cart
  child:
      - id: order_master
        name: Order Master
        url: admin_order
      - id: order_edit
        name: Create Sale Order
        url: admin_order_new
- id: customer
  name: Membership Management
  has_child: true
  icon: cb-users
  child:
      - id: customer_master
        name: Member Master
        url: admin_customer
      - id: customer_edit
        name: Member Register
        url: admin_customer_new

- id: content
  name: Content Management
  has_child: true
  icon: cb-file-text
  child:
      - id: news
        name: News Management
        url : admin_content_news
      - id: file
        name: File Management
        url: admin_content_file
      - id: page
        name: Page Management
        url: admin_content_page
      - id: block
        name: Block Management
        url: admin_content_block
      - id: cache
        name: Cache Management
        url: admin_content_cache
- id: setting
  name: Configuration
  has_child: true
  icon: cb-cog
  child:
      - id: shop
        name: Basic Information Setting
        has_child: true
        child:
            - id: shop_index
              name: Shop Master
              url: admin_setting_shop
            - id: tradelaw
              name: Specified Transaction Law
              url: admin_setting_shop_tradelaw
            - id: customer_agreement
              name: Term of Service Setting
              url: admin_setting_shop_customer_agreement
            - id: shop_payment
              name: Payment method setting
              url: admin_setting_shop_payment
            - id: shop_delivery
              name: Shipping method setting
              url: admin_setting_shop_delivery
            - id: shop_tax
              name: Tax rate setting
              url: admin_setting_shop_tax
            - id: shop_mail
              name: Mail setting
              url: admin_setting_shop_mail
            - id: shop_csv
              name: CSV output item setting
              url: admin_setting_shop_csv
      - id: system
        name: System Info Setting
        has_child: true
        child:
            - id: system_index
              name: System Info
              url: admin_setting_system_system
            - id: member
              name: Member Management
              url: admin_setting_system_member
            - id: authority
              name: Authority Management
              url: admin_setting_system_authority
            - id: security
              name: Security Management
              url: admin_setting_system_security
            - id: log
              name: Log
              url: admin_setting_system_log
            - id: masterdata
              name: Master Data Management
              url: admin_setting_system_masterdata
- id: store
  name: Owner's Store
  has_child: true
  icon: cb-info-circle
  child:
  - id: plugin
    name: Plugin
    has_child: true
    child:
        - id: plugin_list
          name: Plugin List
          url: admin_store_plugin
        - id: plugin_owners_install
          name: Purchased Plugin
          url: admin_store_plugin_owners_install
        - id: plugin_handler
          name: Advanced Setting
          url: admin_store_plugin_handler
  - id: template
    name: Template
    has_child: true
    child:
      - id: template_list
        name: Template List
        url: admin_store_template
      - id: template_install
        name: Upload
        url: admin_store_template_install
  - id: authentication_setting
    name: Authentication key setting
    url: admin_store_authentication_setting
